<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

use Drupal\Core\Recipe\InputCollectorInterface;
use Drupal\Core\Recipe\Recipe;
use Drupal\Core\Recipe\RecipeRunner;
use Drupal\Core\TypedData\DataDefinitionInterface;

/**
 * Implements hook_install().
 */
function websecurity_install() {
  $default_recipe = Recipe::createFromDirectory(__DIR__ . '/recipes/default');
  // Use the default value of every recipe input, such as the site UUID.
  $default_recipe->input->collectAll(new class implements InputCollectorInterface {

    /**
     * {@inheritdoc}
     */
    public function collectValue(string $name, DataDefinitionInterface $definition, mixed $default_value): mixed {
      return $default_value;
    }

  });
  RecipeRunner::processRecipe($default_recipe);
}
